import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { createServiceClient } from "@/lib/supabase/service";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ orgSlug: string }> }): Promise<Metadata> {
  const { orgSlug } = await params;
  const org = await loadOrg(orgSlug);
  return {
    title: `Terms Of Service · ${org?.name ?? "Next Surplus Customer"}`,
    robots: { index: true, follow: false },
  };
}

type OrgSummary = { name: string; legal_name: string | null; website: string | null; email: string | null };

async function loadOrg(slug: string): Promise<OrgSummary | null> {
  const sb = createServiceClient();
  const { data } = await sb
    .from("orgs")
    .select("name, legal_name, website, email")
    .eq("id", slug)
    .maybeSingle();
  return (data as OrgSummary | null) ?? null;
}

export default async function TermsPage({ params }: { params: Promise<{ orgSlug: string }> }) {
  const { orgSlug } = await params;
  const org = await loadOrg(orgSlug);
  if (!org) notFound();

  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const companyName = org.legal_name ?? org.name;

  return (
    <main className="mx-auto max-w-[760px] px-8 py-16 text-[#0a0d14]" style={{ fontFamily: "Inter, system-ui, sans-serif", lineHeight: 1.6 }}>
      <div className="text-[12px] uppercase tracking-[0.14em] text-[#9298a3]">Terms Of Service</div>
      <h1 className="mt-2 text-[28px] font-semibold tracking-[-0.018em]">{companyName}</h1>
      <p className="mt-1 text-[13px] text-[#5b606a]">Effective {today}</p>

      <Section title="Acceptance">
        <p>By engaging {companyName} and signing the retainer we provide, you agree to these terms. If you do not agree, do not retain us.</p>
      </Section>

      <Section title="What We Do">
        <p>{companyName} identifies parties potentially entitled to surplus funds from foreclosure, tax, or other court-supervised sales, contacts them, and assists with the claim process in exchange for a contingency fee disclosed in your signed retainer.</p>
      </Section>

      <Section title="Fees">
        <p>Fees are contingent. You owe nothing unless and until we recover funds on your behalf. The exact contingency rate is set out in your individual retainer agreement.</p>
      </Section>

      <Section title="Communications">
        <p>By providing your phone number you consent to receive calls, voicemails, and (if you opt in) SMS related to your claim. Reply STOP to any SMS to opt out. Standard message and data rates may apply.</p>
      </Section>

      <Section title="Limits Of Service">
        <p>{companyName} is not a law firm. We work with licensed attorneys when legal representation is required. We make no guarantee of recovery, amount, or timing.</p>
      </Section>

      <Section title="Disputes">
        <p>Any dispute will be governed by the laws of the state in which {companyName} maintains its principal office and resolved exclusively in courts of that jurisdiction.</p>
      </Section>

      <Section title="Contact">
        <p>{companyName}{org.email ? <><br />Email: <a href={`mailto:${org.email}`} className="text-[#0d4b3a]">{org.email}</a></> : null}</p>
      </Section>

      <p className="mt-10 border-t border-[#ebedf0] pt-6 text-[11.5px] text-[#9298a3]">
        These terms are generated by Next Surplus for {companyName} based on information they provided. Last updated {today}.
      </p>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-[18px] font-semibold tracking-[-0.014em]">{title}</h2>
      <div className="mt-3 text-[14px] text-[#0a0d14]">{children}</div>
    </section>
  );
}
